### ISSUE TITLE
Getting exception in version 7.10.1 

### ISSUE THREAD

**Issue by safayatborhan** [CodeMazeBlog/elasticsearch-aspnet-core#1]
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"The bulk request must be terminated by a newline [\\n]"}],"type":"illegal_argument_exception","reason":"The bulk request must be terminated by a newline [\\n]"},"status":400}

Getting this exception while executing this command : 
`curl -XPOST localhost:9200/books/book/_bulk --data-binary @sample-data.json -H "Content-Type: application/json"`

**Comment by TimCollins** [comment]
It looks like your sample-data.json might be invalid. Make sure you are passing a valid JSON file to the bulk import command.
